Draft: feat: Added alias lookup
joke/zim-kubectl pull request #21
Opened 2022-09-23 22:17 UTC by kiesman99

Alias lookup functionality highly inspired by [zimfw/git](https://github.com/zimfw/git/blob/master/functions/git-alias-lookup)

2022-09-24 08:54 UTC, joke requested changes

2022-09-24 08:54 UTC, joke commented on init.zsh
> +  alias ${kprefix}\?="kubectl-alias-lookup $1"
```suggestion
  alias "${kprefix}?=kubectl-alias-lookup $1"
```

2022-09-24 08:54 UTC, joke commented on init.zsh
> +  alias ${kprefix}\?="kubectl-alias-lookup $1"
A little bit easier to read.

2022-09-24 09:00 UTC, joke commented on functions/kubectl-alias-lookup
> +  print -u2 "usage: ${0} <path to git module> [pattern...]"
```suggestion
  print -u2 "usage: ${0} <path to kubectl module> [pattern...]"
```

2022-09-24 16:23 UTC, kiesman99 commented
The [original Version](https://github.com/zimfw/git/blob/master/functions/git-alias-lookup) includes the descriptions provided in the [README](https://github.com/zimfw/git).

If you want descriptions, we could add them in the table and extract them.

2022-09-24 16:24 UTC, kiesman99 commented
> The [original Version](https://github.com/zimfw/git/blob/master/functions/git-alias-lookup) includes the descriptions provided in the [README](https://github.com/zimfw/git).
> 
> If you want descriptions, we could add them in the table and extract them.

@joke Here an example:

```bash
❯ G? amend
Gcf  git commit --amend --reuse-message HEAD                          amends the tip of the current branch reusing the same log message as *HEAD*.
GcF  git commit --verbose --amend                                     amends the tip of the current branch.
GrS  git rebase --exec "git commit --amend --no-edit --no-verify -S"  rebases and GPG-signs the commits.
```

2022-09-25 13:52 UTC, joke approved these changes

2022-09-25 13:52 UTC, merged